In [1]:
import numpy as np
A=np.array([[2,-2,3],[1,1,1],[1,3,-1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [2]:
#calculate Eigen values and Eigen vectors.
values,vector=np.linalg.eig(A)

In [3]:
print(values)

[ 3.  1. -2.]


In [4]:
print(vector)

[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [6]:
#eigen values of digonal matrix is diagonal elements itself. And eigen vector is diagonal matrix.
#e.g
import numpy as np
B=np.array([[2,0,0],[0,1,0],[0,0,-1]])
print(B)

[[ 2  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [9]:
egn_val,egn_vect=np.linalg.eig(B)
print(egn_val)
print(egn_vect)

[ 2.  1. -1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
