# What is SVD:-
    A=USV^T
    U-m*m orthogonal matrix (m-rows)
    S-m*n diagoanl some matrix
    Vn*n^T- orthogonal matrix (n-rows)

In [16]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

In [17]:
a=np.array([[1,2,3,4],[1,1,2,3],[0,1,1,0]])
a

array([[1, 2, 3, 4],
       [1, 1, 2, 3],
       [0, 1, 1, 0]])

# THE SVD of A3*4=[3*3][S][4*4]

In [20]:
u,s,vh=np.linalg.svd(a,full_matrices=True)
u

array([[ 0.8109, -0.0934,  0.5776],
       [ 0.57  ,  0.3493, -0.7437],
       [ 0.1323, -0.9324, -0.3365]])

# To check whether the matrix is orthogonal or not!. Its dot product and transpose of matrix result should be Identity matrix.

In [19]:
vh
vh.dot(vh.T)

array([[ 1.,  0.,  0., -0.],
       [ 0.,  1.,  0., -0.],
       [ 0.,  0.,  1., -0.],
       [-0., -0., -0.,  1.]])

In [22]:
#Sd diagoanl matrix
sd=np.diag(s)
sd

array([[6.7509, 0.    , 0.    ],
       [0.    , 1.1734, 0.    ],
       [0.    , 0.    , 0.2186]])

In [26]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
b[:,:-1]=sd
sigma=b
sigma

array([[6.7509, 0.    , 0.    , 0.    ],
       [0.    , 1.1734, 0.    , 0.    ],
       [0.    , 0.    , 0.2186, 0.    ]])

# reconstruct matrix A having product of U,S,Vh

In [33]:
a1=np.dot((np.dot(u,sigma)),vh)
a1

array([[1., 2., 3., 4.],
       [1., 1., 2., 3.],
       [0., 1., 1., 0.]])