# Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([43,32,43,55,56,23])

In [4]:
a.shape

(6,)

In [5]:
a.itemsize

4

In [6]:
a.ndim

1

In [7]:
a.size

6

# #Array creation

In [12]:
np.empty([2,2],dtype='i1')

array([[1, 1],
       [1, 1]], dtype=int8)

In [15]:
np.zeros([2,2],dtype='i1')

array([[0, 0],
       [0, 0]], dtype=int8)

In [16]:
np.ones([2,2],dtype='i1')

array([[1, 1],
       [1, 1]], dtype=int8)

In [19]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# #Generating Random Values And Array

In [21]:
arr=np.random.rand()
print(arr)

0.9292678019725082


In [22]:
arr1=np.random.randn(10)

In [23]:
print(arr1)

[-0.48911155 -0.11040001  0.75629178 -0.37395523 -1.73849866  0.91720023
 -2.91257928  0.04651899  1.58157658  1.60525376]


In [25]:
arr2=np.random.randint(90,size=100)
print(arr2)

[27  3 73 48 16 12 63  1 16 10  6 57 75 54  5 82 28  1 84  9 81 61 23 37
 76 44 41 68 57 40  0 63 51 17 19 22 63 66 51 47  0  0 23 58 55 22 15 45
 56 62 86 69  4 21 46 77 85 38 85 62 11 63 72 66 16 37 45 43 52 74 62 30
 10 28 83 83 39 53 71 44 69  3 54 88 35 82  3 67 32 84 81  2  4 47 21 70
 48 34 46 42]


# #Important Methods

In [26]:
print(arr2.min())

0


In [28]:
print(arr2.max())

88


In [31]:
arr2.sort()
arr2

array([ 0,  0,  0,  1,  1,  2,  3,  3,  3,  4,  4,  5,  6,  9, 10, 10, 11,
       12, 15, 16, 16, 16, 17, 19, 21, 21, 22, 22, 23, 23, 27, 28, 28, 30,
       32, 34, 35, 37, 37, 38, 39, 40, 41, 42, 43, 44, 44, 45, 45, 46, 46,
       47, 47, 48, 48, 51, 51, 52, 53, 54, 54, 55, 56, 57, 57, 58, 61, 62,
       62, 62, 63, 63, 63, 63, 66, 66, 67, 68, 69, 69, 70, 71, 72, 73, 74,
       75, 76, 77, 81, 81, 82, 82, 83, 83, 84, 84, 85, 85, 86, 88])

In [32]:
arr2.argmax()

99

In [33]:
arr2.argmin()

0

In [36]:
np.unique(arr2)

array([ 0,  1,  2,  3,  4,  5,  6,  9, 10, 11, 12, 15, 16, 17, 19, 21, 22,
       23, 27, 28, 30, 32, 34, 35, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 51, 52, 53, 54, 55, 56, 57, 58, 61, 62, 63, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 81, 82, 83, 84, 85, 86, 88])

In [37]:
arr2.mean()

44.0

In [38]:
arr2.std()

26.525082469240317

In [39]:
arr2.var()

703.58

In [43]:
np.cov(arr2)

array(710.68686869)

In [44]:
np.corrcoef(arr2)

1.0